#!/system/bin/sh
# LHD/GPSD Killer to fix Location and offline location issues
# When the script runs it will disable GPS for one second until services reboot

RUN=/sbin/busybox;
LOGFILE=/data/helios/gps.log

log_print() {
  echo "$1"
  echo "$1" >> $LOGFILE
}

log_print ""
mount -o rw,seclabel,remount rootfs /
while true; do
log_print "------------------------------------------------------"
log_print "**helios GPS Killer script started at $( date +"%d-%m-%Y %H:%M:%S" )**"
log_print "------------------------------------------------------"
sleep 5
killall -9 lhd
killall -9 gpsd
log_print "**GPS and LHD have been killed! at $( date +"%d-%m-%Y %H:%M:%S" )**"
sleep 1
start lhd
start gpsd
log_print "**GPS and LHD have been started! at $( date +"%d-%m-%Y %H:%M:%S" )**"
log_print "Backup previous logcat"
if [ -e /data/helios/gps.log ]; then
  cp "/data/helios/gps.log" "/data/heliosLogcat/gps$(date +"%d-%m-%Y %H:%M:%S").log"
fi
   sleep 3600
done
mount -o ro,seclabel,remount rootfs /
